---
# ------------------------------------------------------------------------
# CONFIGURE IPSEC VPN
# ------------------------------------------------------------------------
- hosts: firewalls
  connection: local
  gather_facts: False
  become: False
  collections:
    - paloaltonetworks.panos
    - ansible.utils

  tasks:
    - name: Create tags
      panos_tag_object:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        color: "{{ item.color }}"
        comments: "{{ item.comments }}"
      loop: "{{ tags }}"

    - name: Create shared address objects universal to all firewalls
      panos_address_object:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        address_type: "{{ item.address_type }}"
        value: "{{ item.value }}"
        description: "{{ item.description }}"
        tag: "{{ item.tag }}"
      loop: "{{ shared_address_objects }}"

    - name: Create address objects local to a specific firewall
      panos_address_object:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        address_type: "{{ item.address_type }}"
        value: "{{ item.value }}"
        description: "{{ item.description }}"
        tag: "{{ item.tag }}"
      loop: "{{ local_address_objects }}"

    - name: Create ethernet interfaces
      panos_interface:
        provider: "{{ provider }}"
        if_name: "{{ item.name }}"
        mode: "{{ item.mode }}"
        ip: "{{ item.ip }}"
        enable_dhcp: "{{ item.dhcp }}"
        zone_name: "{{ item.zone }}"
      loop: "{{ ifaces }}"

    - name: Create IPsec VPN tunnel interfaces
      panos_tunnel:
        provider: "{{ provider }}"
        if_name: "{{ item.name }}"
        ip: "{{ item.ip }}"
        zone_name: "{{ item.zone }}"
        vr_name: "{{ item.vr_name }}"
      loop: "{{ tunnels }}"

    - name: Create IKE crypto profiles
      panos_ike_crypto_profile:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        dh_group: "{{ item.dh_group }}"
        authentication: "{{ item.authentication }}"
        encryption: "{{ item.encryption }}"
        lifetime_seconds: "{{ item.lifetime }}"
      loop: "{{ crypto_profiles }}"

    - name: Create IKE gateway config to the firewall
      panos_ike_gateway:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        interface: "{{ item.interface }}"
        enable_passive_mode: "{{ item.enable_passive_mode }}"
        enable_liveness_check: "{{ item.enable_liveness_check }}"
        liveness_check_interval: "{{ item.liveness_check_interval }}"
        peer_ip_value: "{{ item.peer_ip_value }}"
        pre_shared_key: "{{ item.pre_shared_key }}"
        ikev2_crypto_profile: "{{ item.ike_profile }}"
      loop: "{{ ike_gateways }}"

    - name: Create IPSec crypto config to the firewall
      panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        esp_authentication: "{{ item.authentication }}"
        esp_encryption: "{{ item.encryption }}"
        lifetime_seconds: "{{ item.lifetime }}"
      loop: "{{ ipsec_profiles }}"

    - name: Create IPSec tunnel to IKE gateway profile
      panos_ipsec_tunnel:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        tunnel_interface: "{{ item.tunnel }}"
        ak_ike_gateway: "{{ item.gateway }}"
        ak_ipsec_crypto_profile: "{{ item.profile }}"
      loop: "{{ ipsec_tunnels }}"

    - name: Create static default route
      panos_static_route:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        destination: "{{ item.destination }}"
        nexthop: "{{ item.nexthop }}"
        virtual_router: "{{ item.vr }}"
      loop: "{{ routes.static }}"
