---
#------------------------------------------------------------------------
# CHECK TO SEE IF PANORAMA WOULD ALLOW ME TO CREATE A SECURITY OBJECT
#------------------------------------------------------------------------
- hosts: 10.0.131.80
  connection: local
  gather_facts: False
  become: False
  collections:
    - paloaltonetworks.panos
    - ansible.utils

  tasks:
    - name: "Validate that Panorama would allow us to create an object, check mode"
      panos_address_object:
        provider:
          ip_address: "10.0.131.80"
          username: "vannapa"
          password: "Aira@143143143"
        vsys: 'vsys1'
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
        check_mode: yes
        commit: yes 
      register: commit_result

    - name: "Print result to the console"
      debug:
        msg: "{{ result }}"
