---
- hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: "Validate that Panorama would allow us to create an object, check mode"
      panos_address_object:
        ip_address: "10.0.131.80"
        username: "vannapa"
        api_key: "LUFRPT1uNGEvNVhlQzZadmpPUkgyUjRKUGRFdzhuVmM9M1hpNTlUWVJjZWFoTy8ycCtmRHJoaHIyU1hBM1FXL1hUbzNGMGFvbm1kVzNUeThDWEVRQmVEQnA2aTBqT0RMaQ=="
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
        device_group: "AL-PA5220"
      register: result

    - name: "Print result to the console"
      debug:
        msg: "{{ result }}"
