---
- name: Create Device Group in a Specific VSYS
  hosts: 10.0.131.80
  gather_facts: no
  collections:
    - paloaltonetworks.panos
    - ansible.utils
  
  tasks:
    - name: Create a new device group in specified VSYS
      panos_object:
        ip_address: "10.10.10.245"
        username: "Gobi"
        password: "ITCE_1234"
        name: "{{ object_vsys }}"
        #vsys: 'vsys1'  # Specify the VSYS here
        object_type: 'address-group'
        name: 'New_Device_Group'
        description: 'Description of the device group'
        # Additional required parameters...
      register: result

    - name: Display the result
      debug:
        var: result
