---
- name: Validate, create, and commit PAN-OS object
  hosts: firewalls
  gather_facts: false
  tasks:
    - name: Check Panorama operational mode
      panos_op:
        provider:
          ip_address: "10.10.10.233"
          username: "Gobi"
          password: "ITCE_1234"
        cmd: "show"
        cmd_type: "op"
        args:
          cmd_str: "op state"
      register: op_state_result

    - name: Print Panorama operational mode
      debug:
        var: op_state_result.stdout_lines

    - name: Create address object in commit mode
      panos_address_object:
        provider:
          ip_address: "10.10.10.233"
          username: "Gobi"
          password: "ITCE_1234"
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
        vsys: "vsys1"
        device_group: "shared"
        state: "present"
        commit: true
        port: 443
      register: result

    - name: Print the result
      debug:
        var: result
