---
- name: Create Device Group in a Specific VSYS
  hosts: [your_target_hosts]
  gather_facts: no

  tasks:
    - name: Create a new device group in specified VSYS
      panos_object:
        ip_address: "10.0.131.80"
        username: "vannapa"
        password: "Aira143143143"
        vsys: 'vsys1'  # Specify the VSYS here
        object_type: 'address-group'
        name: 'New_Device_Group'
        description: 'Description of the device group'
        # Additional required parameters...
      register: result

    - name: Display the result
      debug:
        var: result
