- hosts: localhost
  gather_facts: False
  tasks:
    - name: "Retrieve Object Details from Panorama"
      uri:
        url: "https://{{ panorama_ip }}/api/"
        method: GET
        body_format: form-urlencoded
        body: "type=config&action=get&key={{ lookup('env', 'pan_api_key') }}&xpath=/config/your-object-type/entry[@name='{{ object_name }}']"
        validate_certs: no
      register: object_details

    - name: "Parse Object Details"
      set_fact:
        object_exists: "{{ object_details.content | b64decode | from_xml | json_query(query) | length > 0 }}"
      vars:
        query: "your-query-to-extract-object-details"

    - name: "Print Object Details"
      debug:
        var: object_details.content

    - name: "Check if Object Exists"
      debug:
        msg: "Object '{{ object_name }}' exists on Panorama."
      when: object_exists

    - name: "Check if Object Does Not Exist"
      debug:
        msg: "Object '{{ object_name }}' does not exist on Panorama."
      when: not object_exists
