---
- hosts: FW
  connection: local
  gather_facts: False
  become: False
  collections:
    - paloaltonetworks.panos
    - ansible.utils

  tasks:
    - name: "Create address object in commit mode"
      panos_address_object:
        provider:
          ip_address: "10.10.10.233"
          username: "Gobi"
          password: "ITCE_1234"
        name: "Gaming-PC3"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC3"
        state: "present"
        commit: yes
      #when: not result.changed  # Only execute if the check mode did not report changes
      register: commit_result

    - name: "Print commit result to the console"
      debug:
        msg: "{{ commit_result }}"
