- hosts: corp_test_Pan
  connection: local
  gather_facts: False
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: "Create an object in Panorama"
      panos_address_object:
        ip_address: "{{ ansible_host }}"  # Define 'panorama_ip' in AWX or playbook vars
        api_key: "{{ lookup('env', 'PANORAMA_API_KEY') }}"
        name: "{{ object_name }}"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "{{ object_description }}"
        device_group: "Your_Device_Group"

    - name: Commit changes on Panorama
      panos_commit:
        ip_address: "{{ ansible_host }}"  # Reuse 'panorama_ip' variable
        api_key: "{{ lookup('env', 'PANORAMA_API_KEY') }}"

    - name: Push configuration to devices
      panos_commit_firewall:
        ip_address: "{{ ansible_host }}"  # Reuse 'panorama_ip' variable
        api_key: "{{ lookup('env', 'PANORAMA_API_KEY') }}"
        device_group: "Your_Device_Group"
        sync_to_peer: yes
