#------------------------------------------------------------------------
# CHECK TO SEE IF PANORAMA WOULD ALLOW ME TO CREATE A SECURITY OBJECT
#------------------------------------------------------------------------
- hosts: FW
  connection: local
  gather_facts: False
  become: False
  collections:
    - paloaltonetworks.panos
    - ansible.utils

  tasks:
    - name: "Validate that Panorama would allow us to create an object, check mode"
      panos_address_object:
        provider:
          ip_address: "10.10.10.233"
          username: "Gobi"
          password: "ITCE_1234"
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
      check_mode: yes
      commit: true
      register: result

    - name: "Print result to the console"
      debug:
        msg: "{{ result }}"
