---
- name: Configure PAN-OS address object
  hosts: FW
  gather_facts: false
  tasks:
    - name: Create address object
      panos_address_object:
        provider:
          ip_address: "10.10.10.233"
          username: "Gobi"
          password: "ITCE_1234"
        name: "Web_Server"
        value: "192.168.1.10"
        description: "Web Server Address Object"
        tags:
          - web
      register: result

    - name: Print the result
      debug:
        var: result
