---
- name: Configure PAN-OS address object
  hosts: FW
  gather_facts: false
  tasks:
    - name: Create address object
      panos_address_object:
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
        vsys: "vsys1"
        device_group: "shared"
        state: "present"
        port: 443
      register: result

    - name: Print the result
      debug:
        var: result

