- hosts: all
  gather_facts: False

  tasks:
    - name: Retrieve Object Details from Panorama
      uri:
        url: "https://{{ ansible_host }}/api/"
        method: GET
        body_format: form-urlencoded
        body: "type=config&action=get&key={{ lookup('env', 'pan_api_key') }}&xpath=/config/your-object-type/entry[@name='{{ object_name }}']"
        validate_certs: no
      register: object_details

    - name: Store Object Details in a Temp File
      copy:
        content: "{{ object_details.content }}"
        dest: "/tmp/panorama_object_details.xml"
