---
#------------------------------------------------------------------------
# CREATE SECURITY POLICY WITHIN PANORAMA
#------------------------------------------------------------------------
- hosts: panorama.redtail.com
  connection: local
  gather_facts: False
  become: False
  collections:
    - paloaltonetworks.panos
    - ansible.utils

  tasks:
    - name: Add test pre-rule to Panorama
      paloaltonetworks.panos.panos_security_rule:
        provider:
          ip_address: "{{ panorama_hostname }}"
          username: "{{ panorama_username }}"
          api_key: "{{ panorama_api_token }}"
        rule_name: "Permit DMZ to WAN"
        description: "Allow Kubernetes hosts outbound access to the WAN"
        source_zone:
          - "DMZ"
        destination_zone:
          - "WAN"
        source_ip:
          - "k3s"
        source_user:
          - "any"
        destination_ip:
          - "any"
        category:
          - "any"
        application:
          - "any"
        service:
          - "application-default"
        hip_profiles:
          - "any"
        tag_name:
          - "redtail"
          - "dmz"
          - "ansible"
        action: "allow"
        device_group: "branch"
        commit: False
      register: results

    - name: Print results to console
      debug:
        msg: "{{ results }}"
